// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmbpONP_X4VRxun01D_G1ln3fMAHe05-Q',
    appId: '1:48962575145:web:1f0212febecf2d7c4e7538',
    messagingSenderId: '48962575145',
    projectId: 'flutter-bloc-riverpod',
    authDomain: 'flutter-bloc-riverpod.firebaseapp.com',
    storageBucket: 'flutter-bloc-riverpod.firebasestorage.app',
    measurementId: 'G-8HSBPSTFNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NQGiJyeKl0jVl77TDAXS_d_pMuQBs-A',
    appId: '1:48962575145:android:baf4727e5c36df754e7538',
    messagingSenderId: '48962575145',
    projectId: 'flutter-bloc-riverpod',
    storageBucket: 'flutter-bloc-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAFv5Cp98sM2la-oa0uKRV2gELYH5_Mc',
    appId: '1:48962575145:ios:d99411bf568482bf4e7538',
    messagingSenderId: '48962575145',
    projectId: 'flutter-bloc-riverpod',
    storageBucket: 'flutter-bloc-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlocRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAFv5Cp98sM2la-oa0uKRV2gELYH5_Mc',
    appId: '1:48962575145:ios:d99411bf568482bf4e7538',
    messagingSenderId: '48962575145',
    projectId: 'flutter-bloc-riverpod',
    storageBucket: 'flutter-bloc-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlocRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmbpONP_X4VRxun01D_G1ln3fMAHe05-Q',
    appId: '1:48962575145:web:6de37abc5d874e4c4e7538',
    messagingSenderId: '48962575145',
    projectId: 'flutter-bloc-riverpod',
    authDomain: 'flutter-bloc-riverpod.firebaseapp.com',
    storageBucket: 'flutter-bloc-riverpod.firebasestorage.app',
    measurementId: 'G-S3TTKKD22M',
  );
}
